# vpn
vpn:
  asn: gcp asn
  peer_asn: aws asn
  peer_gw_name: aws vpn gateway name
  custom_cidr_set:
    - cidr: 10.xx.xx.xx/19
      set_name: first-etc-set
      subnets:
        - name: psc-and-etc
          bits: 3 # = /24
          index: 0 # 10.10.0.0/24
    - cidr: 35.199.192.0/19
      set_name: gcp-cloud-dns-cidr
      subnets:
        - name: gcp-cloud-dns-cidr
          bits: 0 # = /19
          index: 0 # 35.199.192.0/19
    # - cidr: 10.51.200.0/21
    #   set_name: second-etc-set
    #   subnets:
    #     - name: "test3"
    #       bits: 3 # = /24
    #       index: 0 # 10.51.200.0/24
    #     - name: "test4"
    #       bits: 3 # = /24
    #       index: 1 # 10.51.201.1/24

## metadata
labels:
  country: kr
  region: asia-northeast3
  country_code: kr
  environment: dev
