on:
  push:
    branches:
      - main
    paths-ignore:
      - 'infra/'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'infra/'

name: Deploy GCP Cloud Function

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: '${WORKLOAD_IDENTITY_PROVIDER}'
        service_account: '${SERVICE_ACCOUNT}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: '${FUNCTION_NAME}'
        runtime: '${RUNTIME}'
        entry_point: 'test'
        memory_mb: '256'
        region: 'us-central1'
        source_dir: 'source/'
        project_id: '${PROJECT_ID}'
        description: 'test function'
        timeout: 60
        max_instances: 30
        event_trigger_type: 'providers/cloud.pubsub/eventTypes/topic.publish'
        event_trigger_resource: '${EVENT_TRIGGER_RESOURCE}'
        event_trigger_retry: false

    # Example of using the output
    - id: 'test_url'
      run: 'echo "${{ steps.deploy.outputs.url }}"'

    - id: 'test_version'
      run: 'echo "${{ steps.deploy.outputs.version }}"'

    - id: 'test_runtime'
      run: 'echo "${{ steps.deploy.outputs.runtime }}"'
